### ISSUE TITLE
about miniNext installation and example

### ISSUE THREAD

**Issue by prithviraj6116** [USC-NSL/miniNExT#3]
I followed all the steps in the readme file for installation. Installation seems to have finished. So to test I run start.py from the examples/quagga-ixp/ folder as root. And I have quagga installed, however start.py hangs with "Adding Hosts". Any idea?

OS: Ubuntu 14.04
mininet version: 2.2.0
ovs version: 2.0.2

**Comment by bschlinker** [comment]
Hi there -- have you tried running "sudo mn -c", which cleans up Mininet and its dependencies? (A restart would also achieve the same effect).

It would also be good to know if you're using the mininet VM or if you have installed your own copy of Ubuntu. Can you confirm that Mininet is able to start other topologies successfully?

**Comment by prithviraj6116** [comment]
Hi bschlinker,

Yes I did  clean up with sudo mn -c.

I tried both the ways i.e.
(1) using pre-build mininet VM 
(2) also compiling mininet manually in my Ubuntu 14.04 machine
In both the cases, mininet works properly with different topology and controller configurations. (e.g. sudo mn --topo single,3 Or sudo mn --topo treee,depth=2,fanout=3 --controller remote,ip=x.x.x.x,port=x etc.)

Then, I installed mininext like below on both the VMs
git clone https://github.com/USC-NSL/miniNExT.git
cd miniNext
sudo apt-get install `make deps`
sudo apt-get install quagga
sudo make install

and then I ran the quagga-ixp example but it hangs during the adding hosts.

mininet@mininet-vm:~/miniNExT/examples/quagga-ixp$ sudo python ./start.py 
*\* Creating Quagga network topology
*\* Starting the network
*\* Using Mininet Extended (MiniNExT) Handler
**\* Creating network
**\* Adding controller
**\* Adding hosts:

Thanks
Prithviraj

**Comment by prithviraj6116** [comment]
I debugged this with pdb and here is the trail of my step-in and where it hangs
(1)> /home/mininet/miniNExT/examples/quagga-ixp/start.py(67)<module>()
-> startNetwork()
(2)> /home/mininet/miniNExT/examples/quagga-ixp/start.py(37)startNetwork()
-> net = MiniNExT(topo, controller=OVSController)
(3)> /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininext/net.py(16)**init**()
-> Mininet.**init**(self, _args, *_kwargs)
(4) > /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininet/net.py(167)**init**()
-> Mininet.init()  # Initialize Mininet if necessary
(5)> /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininet/net.py(171)**init**()
-> self.build()
(6)> /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininet/net.py(436)build()
-> self.buildFromTopo( self.topo )
(7)> /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininet/net.py(412)buildFromTopo()
-> self.addHost( hostName, *_topo.nodeInfo( hostName ) )
(8) > /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininet/net.py(223)addHost()
-> h = cls( name, *_defaults )
(9)> /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininext/node.py(53)**init**()
-> BaseNode.**init**(self, name, **params)
(10)> /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininet/node.py(101)**init**()
-> self.startShell()
(11)> /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininext/node.py(101)startShell()
-> self.monitor()
(12) > /home/mininet/miniNExT/examples/quagga-ixp/build/bdist.linux-x86_64/egg/mininet/node.py(309)monitor()
-> data += self.read( 1024 )

After this it hangs

**Comment by rbirkner** [comment]
I have exactly the same problem: It hangs in the read method in node.py of mininet. 
When running mininet on its own, it works (e.g. sudo mn - using the minimal topology). I have tried using sudo mn -c, but it doesn't help. Any idea in the meantime?

This is my setup:
VM: Mininet-2.2.0-150106-ubuntu-14.04-server-i386
Ubuntu 14.04
Mininet 2.2.0
Mininext 1.4.0
OVS 2.0.2

**Comment by prithviraj6116** [comment]
@rbirkner No luck for me yet. I also did not get any reply from miniNExT guys yet.

**Comment by bschlinker** [comment]
Sorry to both of you on this -- this fell through the cracks when I was working on a paper submission. I'll take a look at this in detail this evening; just need to fire up a VM first matching your specifications.

**Comment by bschlinker** [comment]
I can confirm this is a problem new with Mininet 2.2.0. Mininet 2.1.0 does not have this issue.

Will investigate further soon.

**Comment by Madhu94** [comment]
Does the bug not exist in Mininet 2.1.0?

**Comment by rbirkner** [comment]
The bug in miniNExT does not exist for Mininet v2.1.0. If you want to use miniNExT, you have to Mininet v2.1.0. That's what I have been doing.

**Comment by Madhu94** [comment]
Thank you for the quick response.Are you sure? I'm sorry for asking over and over, but its a big file to download. Mininet 2.1.0, I mean.

edit :+1: Thank you so much!! Its working now.

**Comment by bschlinker** [comment]
@Madhu94 -- if you're using Ubuntu, you can easily install mininet 2.1.0 with 
`sudo apt-get install mininet=2.1.0-0ubuntu1`

To check the current version(s) of mininet available via your package manager:
`sudo apt-cache madison ^mininet`

On my system, this returns:
`mininet | 2.1.0-0ubuntu1 | http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages`

You may want to uninstall any other versions of mininet first. I recognize this isn't a good long-term solution, but unfortunately haven't had time yet to push changes to mininet for supporting PID namespaces.

**Comment by Madhu94** [comment]
Its working now! The version was the problem. I was using Mininet 2.2.1.
I have had this problem for over 3 weeks and I managed to stumble across this post only today. Thanks a lot!

**Comment by ChrisCindy** [comment]
@bschlinker could you please fix the bug in Mininet 2.2.0 and above since MiniNext hasn't upgrated for a long time? It's such a good tool.Or just tell us where is the problem, i would try to handle it myself. Thanks a lot :)

**Comment by pushkargarg** [comment]
Knock knock!
Trying to use mininext with mininet 2.1.0, while firing up start.py, it raises the following exception:

File "/usr/local/lib/python2.7/dist-packages/mininext-1.1-py2.7.egg/mininext/node.py", line 103, in startShell
    raise Exception('Unable to determine shell\'s PID')
Exception: Unable to determine shell's PID

Any idea how to fix this?

**Comment by avee137** [comment]
I am trying with mininet vm with the correct version. I still see this issue (the script is stuck at Adding hosts)-

QUAGGA#sudo python start.py 
** Creating Quagga network topology
** Starting the network
** Using Mininet Extended (MiniNExT) Handler
*** Creating network
*** Adding controller
*** Adding hosts:
^CTraceback (most recent call last):
  File "start.py", line 67, in <module>
    startNetwork()



QUAGGA#sudo apt-cache madison ^mininet
   mininet | 2.1.0-0ubuntu1 | http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
